### ISSUE TITLE
Constant

### ISSUE THREAD

**Issue by VB10** [yamisagi/Fashion-App-Clone#1]
https://github.com/yamisagi/Fashion-App-Clone/blob/9b9f0d451d831da50a9549cd7496c16b07d0bb65/lib/widget/dress_card.dart#L19

Cardlar heighleri elle vermemeye calis,
borderleri borderdan extend edip projede tek bir border designi kullan

**Comment by yamisagi** [comment]
Teşekkür ederim hocam gözden kaçırmış olmalıyım biraz kısa sürede yapmaya çalıştım 🙃
