### ISSUE TITLE
Theme Factory

### ISSUE THREAD

**Issue by VB10** [yamisagi/Fashion-App-Clone#2]
https://github.com/yamisagi/Fashion-App-Clone/blob/9b9f0d451d831da50a9549cd7496c16b07d0bb65/lib/theme/theme.dart#L11

benim yazilarimda degindigim bir konu projeler buyudugunda buralari yonetmesi zor oluyor bu sebepten factory design ile yaparsan cok daha iyi gelisir
https://medium.com/flutter-community/flutter-build-theme-with-abstract-factory-method-e07df8f730e2

**Comment by yamisagi** [comment]
Teşekkür ederim hocam ilk işim öğrenip fix yayınlamak olacak 🤗
