### ISSUE TITLE
list index

### ISSUE THREAD

**Issue by VB10** [yamisagi/Fashion-App-Clone#4]
https://github.com/yamisagi/Fashion-App-Clone/blob/9b9f0d451d831da50a9549cd7496c16b07d0bb65/lib/product/item_listtile.dart#L24

index list yollama direk modeli yolla

**Comment by yamisagi** [comment]
Boşu boşuna 2 kez index alıp vermek mantıksız olmuş çok haklısınız hocam 🙃 Düzelltim 😊
