### ISSUE TITLE
Atomic widget

### ISSUE THREAD

**Issue by VB10** [yamisagi/Fashion-App-Clone#7]
https://github.com/yamisagi/Fashion-App-Clone/blob/9b9f0d451d831da50a9549cd7496c16b07d0bb65/lib/product/product_appbar.dart#L22

bu tarz durumlarda extract diyip darkLightWidget yapip icinde if ile eklemekten cekinme kod temizligi ve okuma caisndan

**Comment by yamisagi** [comment]
Düzeltildi
