### ISSUE TITLE
Page 2

### ISSUE THREAD

**Issue by VB10** [yamisagi/Fashion-App-Clone#8]
https://github.com/yamisagi/Fashion-App-Clone/blob/9b9f0d451d831da50a9549cd7496c16b07d0bb65/lib/page/profile_page.dart#L48

- tema kullanimi daha cok olmali
- spaceler sabit degeler olmali
- alt widgetle extract ile cikmali
- localization bol bol

**Comment by yamisagi** [comment]
Alt widget oluşturup kullanmayı unutmuşum, düzeltildi 😊
