### ISSUE TITLE
Constanat ayirimi

### ISSUE THREAD

**Issue by VB10** [yamisagi/Fashion-App-Clone#9]
https://github.com/yamisagi/Fashion-App-Clone/blob/9b9f0d451d831da50a9549cd7496c16b07d0bb65/lib/constant/constant.dart#L18

bir consant icinde her seyi kullanma bunlari muhkaak ayir
assetgen kulalanlbirsin

**Comment by yamisagi** [comment]
Constantlar türüne göre ayrıldı
